#include "arduino_secrets.h"

// M5Atom - Version: Latest 
#include <M5Atom.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "water_level_sensing_arduino_cloud"
  https://create.arduino.cc/cloud/things/0a7e3370-8c31-4f2f-a230-32b2891e36e7 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool m5_button_state;
  bool m5_led_state;
  CloudTime distance_sensor_time_val;
  CloudLength distance_sensor_val;
  CloudElectricPotential pressure_sensor_analog_val;
  int lower_fill_sensor_digital_val;
  CloudElectricPotential upper_fill_sensor_analog_val;
  int upper_fill_sensor_digital_val;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define DISTANCE_SENSOR_TRIG_PIN 19
#define DISTANCE_SENSOR_ECHO_PIN 23
#define PRESSURE_SENSOR_ANALOG_PIN 33
#define LOWER_FILL_SENSOR_DIGITAL_PIN 25
#define UPPER_FILL_SENSOR_ANALOG_PIN 32
#define UPPER_FILL_SENSOR_DIGITAL_PIN 21

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  M5.begin(true, false, true);
  M5.dis.fillpix(0x00ff00);

  pinMode(DISTANCE_SENSOR_TRIG_PIN, OUTPUT);
  pinMode(DISTANCE_SENSOR_ECHO_PIN, INPUT);
  pinMode(PRESSURE_SENSOR_ANALOG_PIN, INPUT);
  pinMode(LOWER_FILL_SENSOR_DIGITAL_PIN, INPUT);
  pinMode(UPPER_FILL_SENSOR_ANALOG_PIN, INPUT);
  pinMode(UPPER_FILL_SENSOR_DIGITAL_PIN, INPUT);

  // // Serial.print("distance_sensor_time_val,pressure_sensor_analog_val,lower_fill_sensor_digital_val,upper_fill_sensor_analog_val,upper_fill_sensor_digital_val\r\n");
  // Serial.print("distance_sensor_val,pressure_sensor_analog_val,lower_fill_sensor_digital_val,upper_fill_sensor_analog_val,upper_fill_sensor_digital_val\r\n");
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

  M5.update();
  m5_button_state = M5.Btn.isPressed();

  digitalWrite(DISTANCE_SENSOR_TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(DISTANCE_SENSOR_TRIG_PIN, LOW);
  distance_sensor_time_val = pulseIn(DISTANCE_SENSOR_ECHO_PIN, HIGH);
  distance_sensor_val = (float(distance_sensor_time_val) / 2) / 29.1;
  pressure_sensor_analog_val = float(analogRead(PRESSURE_SENSOR_ANALOG_PIN)) / 4095 * 5;
  lower_fill_sensor_digital_val = !digitalRead(LOWER_FILL_SENSOR_DIGITAL_PIN);
  upper_fill_sensor_analog_val = float(analogRead(UPPER_FILL_SENSOR_ANALOG_PIN)) / 4095 * 5;
  upper_fill_sensor_digital_val = digitalRead(UPPER_FILL_SENSOR_DIGITAL_PIN);

  // Serial.print("distance_sensor_time_val:"); Serial.print(distance_sensor_time_val); Serial.print(",");
  Serial.print("distance_sensor_val:"); Serial.print(distance_sensor_val); Serial.print(",");
  Serial.print("pressure_sensor_analog_val:"); Serial.print(pressure_sensor_analog_val); Serial.print(",");
  Serial.print("lower_fill_sensor_digital_val:"); Serial.print(lower_fill_sensor_digital_val); Serial.print(",");
  Serial.print("upper_fill_sensor_analog_val:"); Serial.print(upper_fill_sensor_analog_val); Serial.print(",");
  Serial.print("upper_fill_sensor_digital_val:"); Serial.print(upper_fill_sensor_digital_val); Serial.print("\r\n");

  delay(1000);
}


/*
  Since m5_led_state is READ_WRITE variable, onM5LedStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onM5LedStateChange() {
  // Add your code here to act upon m5_led_state change
  if (m5_led_state == 1) {
    M5.dis.fillpix(0x00ff00);
  } else {
    M5.dis.fillpix(0x000000);
  }
}
