#include "arduino_secrets.h"

// M5Atom - Version: Latest
#include <M5Atom.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Arduino_Cloud_M5_test"
  https://create.arduino.cc/cloud/things/953ae441-ab30-40c8-a728-bdf18800cc81

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool M5_button_state;
  bool M5_LED_state;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  M5.begin(true, false, true);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

  M5.update();
  M5_button_state = M5.Btn.isPressed();
}


/*
  Since M5_LED_state is READ_WRITE variable, onM5LedStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onM5LedStateChange() {
  // Add your code here to act upon M5_LED_state change
  if (M5_LED_state == 1) {
    M5.dis.fillpix(0x00ff00);
  } else {
    M5.dis.fillpix(0x000000);
  }
}
