// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char ARDUINO_CLOUD_DEVICE_LOGIN_NAME[]  = "204cbaa1-485d-4596-9668-5362fc55ae96"; // food_level_sensor_node

const char WIFI_SSID[]                = SECRET_WIFI_SSID;                // Network SSID (name)
const char WIFI_PASS[]                = SECRET_WIFI_PASS;                // Network password (use for WPA, or use as key for WEP)
const char ARDUINO_CLOUD_DEVICE_KEY[] = SECRET_ARDUINO_CLOUD_DEVICE_KEY; // Secret device password

void onM5LedStateChange();

bool m5_button_state;
bool m5_led_state;
int distance_sensor_time_val;
float distance_sensor_val;

void initProperties(){

  ArduinoCloud.setBoardId(ARDUINO_CLOUD_DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(ARDUINO_CLOUD_DEVICE_KEY);
  ArduinoCloud.addProperty(m5_button_state, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(m5_led_state, READWRITE, ON_CHANGE, onM5LedStateChange);
  // ArduinoCloud.addProperty(distance_sensor_time_val, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(distance_sensor_val, READ, 2 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(WIFI_SSID, WIFI_PASS);
