#include "secrets.h"

// M5Atom - Version: Latest 
#include <M5Atom.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "distance_sensor_node"
  https://create.arduino.cc/cloud/things/232f3c1f-d84a-4be3-a635-27c2b7aee52c

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool m5_button_state;
  bool m5_led_state;
  int distance_sensor_time_val;
  float distance_sensor_val;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "arduino_cloud_thing_properties.h"

#define DISTANCE_SENSOR_TRIG_PIN 22
#define DISTANCE_SENSOR_ECHO_PIN 19

#include "AdafruitIO_WiFi.h"
AdafruitIO_WiFi adafruit_io(SECRET_ADAFRUIT_IO_USERNAME, SECRET_ADAFRUIT_IO_KEY, SECRET_WIFI_SSID, SECRET_WIFI_PASS);
AdafruitIO_Feed *distance_sensor_val_feed = adafruit_io.feed("distance_sensor_val_feed");

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in arduino_cloud_thing_properties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  M5.begin(true, false, true);
  M5.dis.fillpix(0x00ff00);

  pinMode(DISTANCE_SENSOR_TRIG_PIN, OUTPUT);
  pinMode(DISTANCE_SENSOR_ECHO_PIN, INPUT);

  // // Serial.print("distance_sensor_time_val\r\n");
  // Serial.print("distance_sensor_val\r\n");

  adafruit_io.connect();
  while(adafruit_io.status() < AIO_CONNECTED);
  Serial.println(adafruit_io.statusText());
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

  adafruit_io.run();

  M5.update();
  m5_button_state = M5.Btn.isPressed();

  digitalWrite(DISTANCE_SENSOR_TRIG_PIN, HIGH);
  delayMicroseconds(10);
  digitalWrite(DISTANCE_SENSOR_TRIG_PIN, LOW);
  distance_sensor_time_val = pulseIn(DISTANCE_SENSOR_ECHO_PIN, HIGH);
  distance_sensor_val = (float(distance_sensor_time_val) / 2) / 29.1;

  // /*Serial.print("distance_sensor_time_val:");*/ Serial.print(distance_sensor_time_val); Serial.print("\r\n");
  /*Serial.print("distance_sensor_val:");*/ Serial.print(distance_sensor_val); Serial.print("\r\n");

  distance_sensor_val_feed -> save(distance_sensor_val);

  delay(2000);
}


/*
  Since m5_led_state is READ_WRITE variable, onM5LedStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onM5LedStateChange() {
  // Add your code here to act upon m5_led_state change
  if (m5_led_state == 1) {
    M5.dis.fillpix(0x00ff00);
  } else {
    M5.dis.fillpix(0x000000);
  }
}
